### ISSUE TITLE
Understanding the output plot

### ISSUE THREAD

**Issue by kks-vir** [smarini/tardis-phylogenetics#2]
Hi!
I need some help to understand what is happening with my data and how to improve the output from TARDiS.

Once I run TARDiS and got the follow plot: 
![image](https://user-images.githubusercontent.com/60314223/147010645-0cd2dcaa-be3b-4c42-bebc-f1e192a0fe76.png)

Then I tried to increase the parameter "params.nsamples" (several numbers were tested here) in order to reach a plateau but it did not work. 
Actually, it seems that the higher the number of "params.nsamples" the further it gets from reaching the plateau.

So, there are 2 things I would like to ask:

*1) Could you please explain in more detail the output plot generated by TARDiS? What should I expect to see in that plot?*

*2) What parameters should I change to get a better subsample of my data?*

Thanks in advance!

**Comment by smarini** [comment]
Hi there!

_params.nsamples_ represents the number of genomes you want to subsample. So for example, if you set it to 10, you want to subsample 10 genomes out of the total; if you set it to 100, you want to subsample 100. Finding the optimal subset is harder if the subset is larger--that's probably why it takes more time to reach the plateau if you increase that parameter.

1) It's a visual guide for the user to check how the algorithm tackles the problem with the given parameters. It really, really depends on each single problem and the given computational burden to solve it. There is no fixed rule to say if it's satisfactory or not.

So, reaching the plateau depends on the problem--on the data set you are working with. In general, more genomes in your dataset or more genomes in your subsample equals more calculations to reach the plateau. You can therefore use a larger population (more solution considered at the same time, increasing _params.gensize_), more generations (_params.ngenerations_), or both. The downside is of course that it will require more computational resources and time.

2) Try increasing _params.gensize_ and _params.ngenerations_, but be aware that this implies a higher computational burden.
